language: python
python:
  - 3.5
before_install:
  - pip install codecov
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
script:
  - nosetests -v
after_success:
  - codecov