site_name: HGI JSON Documentation
site_url: https://hgi-json.readthedocs.io
repo_url: https://github.com/wtsi-hgi/python-json
theme: readthedocs
pages:
  - 'index.md'
  - 'setup.md'
  - 'functionality.md'
  - 'notes.md'
  - 'performance.md'
  - 'alternatives.md'
  - 'development.md'
  - 'license.md'